name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: 29.1
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        emacs -Q -batch -l ert -l conner.el -l conner-tests.el -f ert-run-tests-batch-and-exit
